name: Add Discord Redirect Url

on:
  issue_comment:
    types: [created]

jobs:
  main:
    name: Main
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Let's go
        uses: actions/checkout@v3
      - name: âš¡ï¸ Fixed NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: node .github/scripts/add-discord-redirect-url.js ${{ github.event.comment.body }}
